#define TOKEN_ETF                             1
#define TOKEN_ERROR                           2
#define TOKEN_BEGIN                           3
#define TOKEN_STATE                           4
#define TOKEN_END                             5
#define TOKEN_EDGE                            6
#define TOKEN_INIT                            7
#define TOKEN_NUMBER                          8
#define TOKEN_STRING                          9
#define TOKEN_IDENT                          10
#define TOKEN_COLON                          11
#define TOKEN_SORT                           12
#define TOKEN_VALUE                          13
#define TOKEN_TRANS                          14
#define TOKEN_MAP                            15
#define TOKEN_END_OF_LINE                    16
#define TOKEN_STAR                           17
#define TOKEN_SLASH                          18
#define TOKEN_EXPR                           19
#define TOKEN_CONSTANT                       20
#define TOKEN_QUANTIFIER                     21
#define TOKEN_BIN11                          22
#define TOKEN_BIN10                          23
#define TOKEN_BIN9                           24
#define TOKEN_PREFIX9                        25
#define TOKEN_POSTFIX9                       26
#define TOKEN_BIN8                           27
#define TOKEN_PREFIX8                        28
#define TOKEN_POSTFIX8                       29
#define TOKEN_BIN7                           30
#define TOKEN_PREFIX7                        31
#define TOKEN_POSTFIX7                       32
#define TOKEN_BIN6                           33
#define TOKEN_PREFIX6                        34
#define TOKEN_POSTFIX6                       35
#define TOKEN_BIN5                           36
#define TOKEN_PREFIX5                        37
#define TOKEN_POSTFIX5                       38
#define TOKEN_BIN4                           39
#define TOKEN_PREFIX4                        40
#define TOKEN_POSTFIX4                       41
#define TOKEN_BIN3                           42
#define TOKEN_PREFIX3                        43
#define TOKEN_POSTFIX3                       44
#define TOKEN_BIN2                           45
#define TOKEN_PREFIX2                        46
#define TOKEN_POSTFIX2                       47
#define TOKEN_BIN1                           48
#define TOKEN_PREFIX1                        49
#define TOKEN_POSTFIX1                       50
#define TOKEN_LPAR                           51
#define TOKEN_RPAR                           52
#define TOKEN_STATE_VAR                      53
#define TOKEN_EDGE_VAR                       54
#define TOKEN_MU_SYM                         55
#define TOKEN_DOT                            56
#define TOKEN_NU_SYM                         57
#define TOKEN_EXISTS_SYM                     58
#define TOKEN_ALL_SYM                        59
#define TOKEN_IF                             60
#define TOKEN_THEN                           61
#define TOKEN_EDGE_EXIST_LEFT                62
#define TOKEN_EDGE_EXIST_RIGHT               63
#define TOKEN_EDGE_ALL_LEFT                  64
#define TOKEN_EDGE_ALL_RIGHT                 65
#define TOKEN_USER                           66
