#define TOKEN_EXPR                            1
#define TOKEN_MU                              2
#define TOKEN_NU                              3
#define TOKEN_EQUALS                          4
#define TOKEN_AND                             5
#define TOKEN_OR                              6
#define TOKEN_LMUST                           7
#define TOKEN_LMAY                            8
#define TOKEN_RMUST                           9
#define TOKEN_RMAY                           10
#define TOKEN_NOT                            11
#define TOKEN_LBRACKET                       12
#define TOKEN_RBRACKET                       13
#define TOKEN_LPAR                           14
#define TOKEN_RPAR                           15
#define TOKEN_TRUE                           16
#define TOKEN_FALSE                          17
#define TOKEN_DOT                            18
#define TOKEN_STRING                         19
#define TOKEN_ID                             20
#define TOKEN_NUMBER                         21
